// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { StimulusApplication as AnotherSuperWeirdName } from "./application"

import HelloController from "./hello_controller"

AnotherSuperWeirdName.register("hello", HelloController)
application.register("this-shouldnt-register", HelloController)
